package ru.yamsergey.google.cloud.model.syntax;

public enum Case {
  CASE_UNKNOWN,
  ACCUSATIVE,
  ADVERBIAL,
  COMPLEMENTIVE,
  DATIVE,
  GENITIVE,
  INSTRUMENTAL,
  LOCATIVE,
  NOMINATIVE,
  OBLIQUE,
  PARTITIVE,
  PREPOSITIONAL,
  REFLEXIVE_CASE,
  RELATIVE_CASE,
  VOCATIVE
}
